<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn</name>
   <tag></tag>
   <elementGuidId>c8713786-2153-4e80-904a-1d24feadc467</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//button[(text()='${label}')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//button[(text()='${label}')])[1]</value>
      <webElementGuid>26f72849-745a-41cb-b1dd-963db2e90ffb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
