<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>css</name>
   <tag></tag>
   <elementGuidId>a41426f7-c1ef-415b-861c-09ab3d509b4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>${css}</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value> </value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>${css}</value>
      <webElementGuid>b43c8cfd-48e3-4651-ab0d-00dc6c0ca540</webElementGuid>
   </webElementProperties>
</WebElementEntity>
