<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>d3029960-0169-4af2-a2b5-f5517ec4f017</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//*[text()='${label}']/ancestor::*/*[name()='svg'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[text()='${label}']/ancestor::*/*[name()='svg'])[1]</value>
      <webElementGuid>9575235a-d881-42d9-b30b-c23ef4724e5a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
